name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    env:
      CI: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_8987E }}
          channelId: live
          projectId: portfolio-8987e